# fly.toml app configuration file generated for alltodo-api on 2023-09-26T15:58:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alltodo-api"
primary_region = "mia"

[build]
